# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file
# 'C:\Users\Adam\OneDrive\Documents\Scripts\Python\Shotgun\tk-t-sheets\tk-t-sheets\install\manual\tk-t-sheets\
# v0.1.0\resources\clock_out_dialog.ui'
#
# Created: Sun Nov 12 19:03:46 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(612, 458)
        self.verticalLayout_6 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.employee = QtGui.QLabel(Dialog)
        self.employee.setStyleSheet("font: 75 14pt \"Arial\";")
        self.employee.setObjectName("employee")
        self.verticalLayout.addWidget(self.employee)
        self.statement = QtGui.QLabel(Dialog)
        self.statement.setStyleSheet("font: 75 10pt \"Arial\";")
        self.statement.setObjectName("statement")
        self.verticalLayout.addWidget(self.statement)
        self.project_name = QtGui.QLabel(Dialog)
        self.project_name.setObjectName("project_name")
        self.verticalLayout.addWidget(self.project_name)
        self.entity = QtGui.QLabel(Dialog)
        self.entity.setObjectName("entity")
        self.verticalLayout.addWidget(self.entity)
        self.task = QtGui.QLabel(Dialog)
        self.task.setObjectName("task")
        self.verticalLayout.addWidget(self.task)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.start_time_label = QtGui.QLabel(Dialog)
        self.start_time_label.setObjectName("start_time_label")
        self.verticalLayout_2.addWidget(self.start_time_label)
        self.start_time = QtGui.QDateTimeEdit(Dialog)
        self.start_time.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.start_time.setObjectName("start_time")
        self.verticalLayout_2.addWidget(self.start_time)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.current_time_label = QtGui.QLabel(Dialog)
        self.current_time_label.setObjectName("current_time_label")
        self.verticalLayout_3.addWidget(self.current_time_label)
        self.current_time = QtGui.QDateTimeEdit(Dialog)
        self.current_time.setObjectName("current_time")
        self.verticalLayout_3.addWidget(self.current_time)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.total_time_label = QtGui.QLabel(Dialog)
        self.total_time_label.setObjectName("total_time_label")
        self.verticalLayout_4.addWidget(self.total_time_label)
        self.total_time = QtGui.QTimeEdit(Dialog)
        self.total_time.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.total_time.setObjectName("total_time")
        self.verticalLayout_4.addWidget(self.total_time)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.status_grp = QtGui.QGroupBox(Dialog)
        self.status_grp.setStyleSheet("font: 75 10pt \"Arial\";")
        self.status_grp.setObjectName("status_grp")
        self.layoutWidget = QtGui.QWidget(self.status_grp)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 291, 29))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.in_progress = QtGui.QRadioButton(self.layoutWidget)
        self.in_progress.setChecked(True)
        self.in_progress.setObjectName("in_progress")
        self.horizontalLayout_2.addWidget(self.in_progress)
        self.complete = QtGui.QRadioButton(self.layoutWidget)
        self.complete.setObjectName("complete")
        self.horizontalLayout_2.addWidget(self.complete)
        self.verticalLayout_6.addWidget(self.status_grp)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setStyleSheet("font: 75 14pt \"Arial\";")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.yes_btn = QtGui.QPushButton(Dialog)
        self.yes_btn.setStyleSheet("background-color: rgb(0, 255, 0);font: 75 10pt \"Arial\";color: rgb(0, 0, 0);")
        self.yes_btn.setObjectName("yes_btn")
        self.horizontalLayout_3.addWidget(self.yes_btn)
        self.no_btn = QtGui.QPushButton(Dialog)
        self.no_btn.setStyleSheet("background-color: rgb(255, 0, 0);font: 75 10pt \"Arial\";color: rgb(0, 0, 0);")
        self.no_btn.setObjectName("no_btn")
        self.horizontalLayout_3.addWidget(self.no_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.start_time_label.setBuddy(self.start_time)
        self.current_time_label.setBuddy(self.current_time)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.start_time, self.current_time)
        Dialog.setTabOrder(self.current_time, self.complete)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.employee.setText(QtGui.QApplication.translate("Dialog", "Employee Name", None, QtGui.QApplication.UnicodeUTF8))
        self.statement.setText(QtGui.QApplication.translate("Dialog", "You are currently clocked in to:", None, QtGui.QApplication.UnicodeUTF8))
        self.project_name.setText(QtGui.QApplication.translate("Dialog", "Project Name", None, QtGui.QApplication.UnicodeUTF8))
        self.entity.setText(QtGui.QApplication.translate("Dialog", "Asset / Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.task.setText(QtGui.QApplication.translate("Dialog", "Task", None, QtGui.QApplication.UnicodeUTF8))
        self.start_time_label.setText(QtGui.QApplication.translate("Dialog", "Start Time", None, QtGui.QApplication.UnicodeUTF8))
        self.current_time_label.setText(QtGui.QApplication.translate("Dialog", "Current Time", None, QtGui.QApplication.UnicodeUTF8))
        self.total_time_label.setText(QtGui.QApplication.translate("Dialog", "Total Time (hours)", None, QtGui.QApplication.UnicodeUTF8))
        self.total_time.setDisplayFormat(QtGui.QApplication.translate("Dialog", "h:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.status_grp.setTitle(QtGui.QApplication.translate("Dialog", "Are you done with this task?", None, QtGui.QApplication.UnicodeUTF8))
        self.in_progress.setText(QtGui.QApplication.translate("Dialog", "In Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.complete.setText(QtGui.QApplication.translate("Dialog", "Complete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Would you Like to Clock Out?", None, QtGui.QApplication.UnicodeUTF8))
        self.yes_btn.setText(QtGui.QApplication.translate("Dialog", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.no_btn.setText(QtGui.QApplication.translate("Dialog", "No", None, QtGui.QApplication.UnicodeUTF8))

